[workspace]
members = ["pulsar", "shared"]
exclude = ["singularity"]
resolver = "3"

[workspace.dependencies]
env_logger = "0.11.9"
log = "0.4.29"
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Etw",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Services",
    "Win32_System_Time",
    "Win32_System_ProcessStatus",
    "Win32_Storage_FileSystem",
    "Win32_System_IO"
] }
