//! Pipeline event definitions.

use crate::sensors::etw::EventRecord;

/// Represents any telemetry event flowing through the detection and processing pipeline.
#[derive(Debug)]
pub enum Event {
    /// An event generated by the Windows ETW (Event Tracing for Windows) subsystem.
    Etw(EventRecord),
}
