use crate::sensors::etw::EventRecord;

/// Represents any event flowing through the system's detection pipeline.
#[derive(Debug)]
pub enum Event {
    /// An event generated by the Windows ETW subsystem.
    Etw(EventRecord),
}
